databases:
  - name: crypto-db
    plan: free

services:
  - type: web
    name: cryptocurrency-prediction
    runtime: python
    rootDir: code
    buildCommand: "bash build.sh"
    startCommand: "gunicorn cryptocurrency_price_prediction.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
